### ISSUE TITLE
Install of NEM2-CLI under Mac OSX not possible

### ISSUE THREAD

**Issue by ritzeng** [nemtech/nem2-cli#10]
1. Expected behavior and actual behavior.
$ sudo npm install --global nem2-cli

List:
ritz4:~ fr$ sudo npm install --global nem2-cli
/usr/local/bin/nem2-cli -> /usr/local/lib/node_modules/nem2-cli/bin/nem2-cli

bufferutil@3.0.5 install /usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil
prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/Users/fr/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/fr/.node-gyp/8.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil/.node-gyp'
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fr/.npm/_logs/2018-10-29T20_37_59_852Z-debug.log

2. Steps to reproduce the problem.
Login Admin auf Mac OSX 10.13.6
Run command as specified above
Message appear as written above

nem2-cli is not available

3. Specifications like the version of the project, operating system, or hardware.
Mac OSX 10.13.6
All Accounts, Admin or Normal User, also Mac OSX 10.13.6 under Parallels 14 VM

**Comment by Vektrat** [comment]
I don't think this error is related to this repository specifically, please check this link and come back again if you could not fix it - https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by ritzeng** [comment]
i have checked it so far.

About 15-20 Installations went very well while the years. And this one made problems? 
Why should i change something that worked well, possibly getting problems with the other installations? 

I’ll check tomorrow installations which are not global.

Best regards
Frank

**Comment by Vektrat** [comment]
I'm just considering straightforward situations because as you can imagine I cannot personally address every issue anyone can have in a personal way, check this thread, maybe it is more helpful (with the --unsafe-perm flag)

https://github.com/nodejs/node-gyp/issues/454

**Comment by ritzeng** [comment]
Hello Mr. Hernandez,

YES, thank you.

I run from my Admin account: sudo npm install --global nem2-cli --allow-root --unsafe-perm

It worked. 

Thank you very much.

Frank H. Ritz
