### ISSUE TITLE
transfer command ignores message in interactive shell.

### ISSUE THREAD

**Issue by 44uk** [nemtech/nem2-cli#11]
1. Expected behavior and actual behavior.

Expected: In interactive shell, nem2-cli should ask to append message.
Actual: nem2-cli doesn't ask to append message.

2. Steps to reproduce the problem.

```
$ nem2-cli transaction transfer
Introduce the recipient address: SCXXXX-XXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXX
Introduce the mosaics in the format namespaceName:mosaicName::absoluteAmount, add multiple mosaics splitting them with a comma: nem:xem::1000000
Transaction announced correctly
Hash:    33D...
Signer:  CD6...
```

Not asking append message. `Introduce the message:`
https://github.com/nemtech/nem2-cli/blob/master/src/commands/transaction/transfer.ts#L118

3. Specifications like the version of the project, operating system, or hardware.

nem2-cli: 0.9.7

**Comment by dgarcia360** [comment]
Fixed in #57
