### ISSUE TITLE
Render receipts using tables

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#112]
[ReceiptsService ](https://github.com/nemtech/nem2-cli/blob/master/src/service/receipt.service.ts#L24) renders the receipts using plain text. We could use tables using ``cli-table3`` extension.

Example:  https://github.com/nemtech/nem2-cli/blob/master/src/commands/mosaic/info.ts#L34

**Comment by NemTechCN** [comment]
PR #123
