### ISSUE TITLE
Render transactions using tables

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#113]
[TransactionService ](https://github.com/nemtech/nem2-cli/blob/master/src/service/transaction.service.ts#L24) renders the transactions using plain text. We could use tables using ``cli-table3`` extension.

Example:  https://github.com/nemtech/nem2-cli/blob/master/src/commands/mosaic/info.ts#L34

**Comment by NemTechCN** [comment]
PR #124
