### ISSUE TITLE
Add alias support

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#134]
[transfer.ts](https://github.com/nemtech/nem2-cli/blob/master/src/commands/transaction/transfer.ts) is the only command accepting aliased mosaics. The following command should also allow aliased addresses and mosaic ids:

- [x] transaction/transfer: Review recipientAddress (AddressValidator).
- [x] transaction/accountaddressrestriction value
- [x] transaction/accountmosaicrestriction value
- [ ] transaction/mosaicsupplychange mosaicId
- [x] transaction/secretlock mosaicId and recipientAddress
- [x] transaction/secretproof recipientAddress

**Comment by NemTechCN** [comment]
Maybe we should update SDK version first.
