### ISSUE TITLE
nem2-cli profile create command display a "The network provided and the node network don't match."

### ISSUE THREAD

**Issue by cndlhvn** [nemtech/nem2-cli#149]
Hi dear developers

1. Expected behavior and actual behavior.

I run this command `nem2-cli profile create --private-key nemesis-user-private-key-here --network MIJIN_TEST --url http://localhost:3000`, But I receive a message which is  "The network provided and the node network don't match." message . 

2. Steps to reproduce the problem.

Launch a ver 0.9.0.1 catapult-service-bootstrap on the docker, and you run this command `nem2-cli profile create --private-key  nemesis-user-private-key-here --network MIJIN_TEST --url http://localhost:3000`,

3. Specifications like the version of the project, operating system, or hardware.

- Mac mojave
- docker for mac
- nem2-cli v0.15.0
- catapult-service-bootstrap docker v0.9.0.1

4. part of the problem

I go to see the source code for the compiled nem2-cli and find the problem.

In the `nem2-cli/build/src/commands/profile/create.js`,  I debug these two variables `res[0]` and `networkType`. `res[0]` has 175 and `networkType` has 144. 

```js
...
   const networkHttp = new nem2_sdk_1.NetworkHttp(url)
    const blockHttp = new nem2_sdk_1.BlockHttp(url)
    rxjs_1.forkJoin(networkHttp.getNetworkType(), blockHttp.getBlockByHeight('1')).subscribe(
      res => {
        if (res[0] !== networkType) {
          console.log("The network provided and the node network don't match.")
        } else {
...
```

This is a `res` value

```js
[ 175,
  BlockInfo {
    hash:
     '972C01E02AF62F13B882CE18224DEC130D234FD0D4E8EE02178A0A272578C5B7',
    generationHash:
     '792FADFBF51BE0EA883F5473B78DBAE4EA4AF286BBE39E18E1546B9658AA2FCF',
    totalFee: UInt64 { lower: 0, higher: 0 },
    numTransactions: 29,
    signature:
     'D61DD5A2C04EFF6E564BAAAFCC57CF8D000AE6C9634177AD28D1D909ED5F5134A10E3C4C04FC0BAC4F20838C343CE16103BE57E4D81970445A15F152A8232209',
    signer:
     PublicAccount {
       publicKey:
        '1EC0046FB4B6D595A74CDB85E94E643968040CC603A67B6E54315CAA90B1D681',
       address: [Address] },
    networkType: 144,
    version: 1,
    type: 32835,
    height: UInt64 { lower: 1, higher: 0 },
    timestamp: UInt64 { lower: 0, higher: 0 },
    difficulty: UInt64 { lower: 276447232, higher: 23283 },
    feeMultiplier: 0,
    previousBlockHash:
     '0000000000000000000000000000000000000000000000000000000000000000',
    blockTransactionsHash:
     '99AB325D59AB4EE174143E70B655E4208CB0E04EC6E5C41C6B5FA387FA8FF62B',
    blockReceiptsHash:
     '15F43834567BAF7EF857DF03D2A481B124E4041B17081BF103EB5BD2FBEC3999',
    stateHash:
     'B7958E3F282964175B60F01A814886BB31F1A7007BB31368A5CC603A2BE9EAE5',
    beneficiaryPublicKey: undefined } ]
```
 If the value of `res[0]` is changed to `res[1]["networkType"], this problem will be solved probably.

This file also has the same problem. `nem2-cli/build/src/commands/account/generate.js`

**Comment by evias** [comment]
This is a known bug identified in catapult-rest about the nodeInfoCodec but it has been fixed since then ; you should probably update your bootstrap to 0.9.1.1 (latest master commit)

**Comment by dgarcia360** [comment]
@cndlhvn Thanks for the detailed report! In this PR https://github.com/nemtech/nem2-cli/pull/150,  the networkType is picked from the block header. This change should make the nem2-cli compatible with both bootstrap versions and decreases the number of calls from 2 to 1.
