### ISSUE TITLE
Password input: can't use backspace

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-cli#166]
When inputting a password, should be able to delete chars to rectify typing mistakes

**Comment by dgarcia360** [comment]
Related issue: https://github.com/anseki/readline-sync/issues/17

If there is no way to fix it, we might need to evaluate the use of another library in the future. Now it should be quite easy to change the library since the resolvers are detached from the commands.

**Comment by decentraliser** [comment]
closed in favour of #167
