### ISSUE TITLE
Transaction confirmation prompt: should display the transaction fields instead of (only) the payload

### ISSUE THREAD

**Issue by decentraliser** [nemtech/nem2-cli#168]
1. Expected behavior and actual behavior.

![image](https://user-images.githubusercontent.com/36499647/71569522-a8ce9680-2b0a-11ea-81ba-d3bec8bc1d18.png)

here I would expect a summary of the transaction before confirmation, not a payload

**Comment by dgarcia360** [comment]
Partially solved with #171. As an improvement, we could create custom tables for each tx type.

**Comment by NemTechCN** [comment]
> Partially solved with #171. As an improvement, we could create custom tables for each tx type.

What does this mean? Could you please describe more specifically?

**Comment by dgarcia360** [comment]
Each transaction type (e.g. Transfer, MultisigModification, NamespaceRegistration, etc) could have its own table, extending from a general ``TransactionTable``. By doing so, when the user announces a transaction it will see all the fields related with the transaction (e.g. mosaics being sent, message, duration...).

To have them organized, we could create a new folder "/tables/transactions" to keep them all grouped. Besides, tables could be reused to simplify the current ``TransactionService`` and allow us to test every table output separately.

**Comment by decentraliser** [comment]
Ild suggest these to return objects instead of strings

Also, maybe you could consider leveraging console.table

You can have a look at this implementation, that we could adapt if you like
it

https://github.com/nemfoundation/nem2-desktop-wallet/tree/master/src/core/model

**Comment by dgarcia360** [comment]
Closed in favor of #191
