### ISSUE TITLE
Status is not throwing errors

### ISSUE THREAD

**Issue by ugniusvers** [nemtech/nem2-cli#183]
After announcing a transaction a status is expected to throw an error if there is any. This was happening in previous versions of nem2-cli.

This was fixed in nem2-sdk-typescript-javascript, must be checked in cli too.

https://github.com/nemtech/nem2-sdk-typescript-javascript/issues/411
https://github.com/nemtech/catapult-rest/commit/1cf85eba81aea8f74cab0382520c7a48a9830e30

**Comment by dgarcia360** [comment]
Thanks for reporting! We have updated the nem2-sdk dependency and published a new release (0.16.1). If the error still persist, please add a comment on the issue.
