### ISSUE TITLE
transaction status command missing

### ISSUE THREAD

**Issue by aleixmorgadas** [nemtech/nem2-cli#2]
transaction status command should work as follows:

`nem2-cli transaction status --hash <tx_hash>`

or

```text
nem2-cli transaction status
Insert transaction hash: <tx_hash>
```

:warning:  it should also accept the `--profile <profile_name>` argument parameter

It should return the transaction status similar to:

- Success
```
group: confirmed
status: Success
hash: <tx_hash>
deadline: number
height: number
```

- Error
```
group: failed
status: Failure_Core_Insufficient_Balance
hash: <tx_hash>
deadline: number
```

**Comment by NemTechCN** [comment]
https://github.com/nemtech/nem2-cli/pull/41
