### ISSUE TITLE
nem2-cli error install on linux

### ISSUE THREAD

**Issue by luster022** [nemtech/nem2-cli#21]
sudo npm install nem2-cli -g
list: 
/usr/local/bin/nem2-cli -> /usr/local/lib/node_modules/nem2-cli/bin/nem2-cli

> bufferutil@3.0.5 install /usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil/build'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil/build'
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/nem2-cli/node_modules/bufferutil
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tg/.npm/_logs/2019-03-20T07_18_49_769Z-debug.log

2. Steps to reproduce the problem.
execute installation command as administrator
Message appear as written above

3. Specifications like the version of the project, operating system, or hardware.
Elementary OS 5.0 Juno 
Ubuntu 18.04.2 LTS
Node V 10.15.3
npm V 6.9.0

**Comment by dgarcia360** [comment]
Hi there, it seems we missed this issue.

I’m closing this issue _for now_ because of inactivity, as we did not receive other similar errors.

@luster022  we can always reopen it though! :)
