### ISSUE TITLE
Support account restriction transaction

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#27]
# Specification

This specification would only allow adding/removing one mosaic/address/entity type at a time. 

Please, comment on the issue if you have an idea to support multiple actions at a time.

## AccountAddressRestrictionTransaction

Allow or block incoming and outgoing transactions for a given a set of addresses.

### Command

``nem2-cli transaction accountaddressrestriction``

| param | type | description | default | 
| -- | -- | -- | -- |
| --profile | string | (Optional) Select between your profiles, by providing a profile  | default |
| --maxfee | uint | (Optional) Maximum fee | 0 |
| --restrictionType | string | allow/block | |
| --restrictionDirection | string | (Optional)  incoming/outgoing| incoming |
| -- modificationAction | uint | Modification action. (1: Add, 0: Remove) | | 
| -- value | string | Address to allow/block | |

## AccountMosaicRestrictionTransaction

Allow or block incoming transactions containing a given set of mosaics.

``nem2-cli accountmosaicrestriction``

### Command

| param | type | description | default | 
| -- | -- | -- | -- |
| --profile | string | (Optional) Select between your profiles, by providing a profile  | default |
| --maxfee | uint | (Optional) Maximum fee | 0 |
| --type | string | allow/block | |
| -- modificationaction | uint | Modification action. (1: Add, 0: Remove) | | 
| -- value | string | Mosaic identifier to allow/block | |

## AccountOperationRestrictionTransaction

Allow or block outgoing transactions by transaction type.

### Command

``nem2-cli accountoperationrestriction``

| param | type | description | default | 
| -- | -- | -- | -- |
| --profile | string | (Optional) Select between your profiles, by providing a profile  | default |
| --maxfee | uint | Maximum fee | 0 |
| --type | string | allow/block | |
| --direction | string | (Optional)  incoming/outgoing| incoming |
| --modificationaction | uint | Modification action. (1: Add, 0: Remove) | | 
| -- value | string | Operation type to allow/block | |

**Comment by NemTechCN** [comment]
I've seen that this needs to be upgraded to the SDK version in order to continue.

**Comment by dgarcia360** [comment]
@NemTechCN Specification updated ^^

**Comment by BuBuHighLighter** [comment]
@dgarcia360 

 I don't know how to use the parameter `restrictionType` In **AccountOperationRestrictionTransaction**.Because the class of transaction type doesn't have 'allow' or 'block'.

[the class of transaction type](https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/transaction/TransactionType.ts)

***
I use the `SDK@0.13.0`

**Comment by NemTechCN** [comment]
PR #100
