### ISSUE TITLE
Add a converter module

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#29]
**USAGE**

  nem2-cli converter

**SUBCOMMANDS**

  hexToAddress - Converts a hexadecimal address to a base 32 address
  addressToHex - Converts a base32 address to hex address
  hexToUint - Converts a hexadecimal id to a uint64 object
  uintToHex- Converts a hexadecimal mosaic to a uint64 object

**Comment by NemTechCN** [comment]
https://github.com/nemtech/nem2-cli/pull/39
