### ISSUE TITLE
Remark if a mosaic or namespace is expired / close to expire

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#31]
When running ``nem2-cli account info``, the mosaic should display in how many blocks the mosaic will expire, or if it is actually expired.

**Comment by NemTechCN** [comment]
I want to know how to get the Mosaic Properties property, which is private. Mosaic Properties. duration

**Comment by BuBuHighLighter** [comment]
PR  #86 
Mosaic expiration time
