### ISSUE TITLE
Add cosign aggregate transactions command

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#4]
**Description**

At the moment, it is quite challenging to cosign transactions while testing the Catapult Developer Preview. Every time an account has to cosign an aggregate bonded transaction, a developer should develop and run a custom program.

https://nemtech.github.io/guides/transaction.html#signing-announced-aggregate-bonded-transactions

**Proposed solution**

1) Add transaction hash when listing  transactions using nem2-cli:

nem2-cli account aggregatebonded
nem2-cli monitor aggregatebonded
..

2) Include a new command  `nem2-cli transaction cosign`.

USAGE

nem2-cli transaction cosign [...options]

OPTIONS

--profile <profile>         - (Optional) Select between your profiles, by providing a profile name
-h, --hash <hash> - Transaction hash to be cosigned

**Comment by guillemsole** [comment]
Added in v0.9.5
