### ISSUE TITLE
cross-network replay protection

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#42]
When hashing/signing/verifying an entity prepend the network guid (network generation hash) to the data payload.

**Comment by evias** [comment]
Generation hash was included in `sign` logic in the SDK.

- Transaction.signWith: https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/154/files#diff-d68c0810039fb8c410b4c768978c6230R88

- Account.sign: https://github.com/nemtech/nem2-sdk-typescript-javascript/pull/154/files#diff-9a881ed1e0db079aaf22009196c93390R133

**Comment by dgarcia360** [comment]
Solved here https://github.com/nemtech/nem2-cli/pull/43
