### ISSUE TITLE
Exporting NEM2_PROFILE to named profile does not work

### ISSUE THREAD

**Issue by vazudew** [nemtech/nem2-cli#48]
1. Expected behavior and actual behavior.

a)  export NEM2_PROFILE=xxx accepts named profile as per documentation instead of default. But in reality the nem2-cli still works with default
Source : https://nemtech.github.io/cli.html

3. Specifications like the version of the project, operating system, or hardware.
Ubuntu : 18.04
Nem2cli : 0.12.1

**Comment by dgarcia360** [comment]
Thanks for reporting the issue!

I have reproduced it in Windows as well, and I can confirm that is not working.

We'll remove this from the docs temporarily until the issue is fixed.

**Comment by BuBuHighLighter** [comment]
@dgarcia360 
I can't quite understand the problem.
Is it true that setting the export file name does not take effect or setting the default profile name?
And could you tell me how to reproduce it in Windows?

**Comment by dgarcia360** [comment]
Setting the variable "NEM2_PROFILE=<profile_name>" does not make "profile_name" the [default profile](https://github.com/nemtech/nem2-cli/blob/7d88e5db373ed7916062f612bb5e3a1db1b14782/src/profile.command.ts#L35).

**How to reproduce it in Windows**

1. Open PowerShell with nem2-cli installed
2. Create two different profiles named "A" and "B" with ``nem2-cli account generate --save``.
3. ``Set-Variable -Name "NEM2_PROFILE" -Value "B"``
4. Try to announce a transaction without specifying a profile. Transaction will be send from the original default "A" and not from "B".

**Comment by BuBuHighLighter** [comment]
Profile name #72
