### ISSUE TITLE
Account info for non default/account does not work

### ISSUE THREAD

**Issue by vazudew** [nemtech/nem2-cli#49]
Ubuntu : 18.04
Nem2cli : 0.12.1
Docker :  18.09.7 Build 2d0083d 
(Installation Info: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04 )
Docker-Compose : 1.21.2 Build a133471

Steps
1) catapult-service-bootstrap.git latest cloned and readied
2) exeucted start-all -b -d successfully, all dockers are up
3) valid output received for curl http://localhost:3000/block/1
4) from the address.yaml, grabbed a private key below nemesis_address section
5) created a "default" profile on http://localhost:3000, with Private key from step 4
6) nem2-cli account info gave correct information regarding default profile
7) generated new account/profile with commands
$ nem2-cli account generate --network MIJIN_TEST -s --url http://localhost:3000 --profile test1
$ nem2-cli profile create -p  <PRIVATE_KEY_FROM_ADDRESS.YAML>-n MIJIN_TEST -u http://localhost:3000
8) verified the profiles/account exist with command nem2-cli profile list

FAILURES
a)  $nem2-cli account info --profile <NameOfAccountOrProfile> 
b) $ nem2-cli account info --address <ADDRESSOfAccountOrProfile>
gives always the error 
code: ResourceNotFound 
message : no Resource exists with ID <Address>
However the information shown for default profile is correct.

ALTERNATE
a) I executed transfer transaction as follows
nem2-cli transaction transfer --recipient <ADRESSofNonDefaultAccount> --message "payout of 10 xem" --mosaics @cat.currency::10000000 
transaction was successful, with hash and signer information
But still  $nem2-cli account info --profile, --address FAILED

**Comment by dgarcia360** [comment]
Hi @vazudew,

To use the command with the ``address`` tag, you should provide a valid address as well.

For example, try with ``nem2-cli account info --address SCBJQVLUBEA3VJXPGXERZ4ANABMSCK7UT65OYMTX``, replacing the address for the one you want to check.

⚠️ The address you are querying must have issued or received a transaction, if not the network won't know about it. 

Let me know if you have still problems with the command.

**Comment by vazudew** [comment]
Sorry for incomplete information, i mean both of the following commands gave me the error
$$ nem2-cli account info --profile <PROFILE_NAME> 
$ nem2-cli account info --address <ADDRESS>

**Comment by rg911** [comment]
Try announce a transfer transaction to this new account you generate first. using nemesis account (you default profile) as signer.  Make sure you have read the comment from @dgarcia360

**Comment by vazudew** [comment]
My source : https://nemtech.github.io/cli.html

I have done following steps 
a) created a default profile  (nemesis), ensured the profile to exist with commands $ nem2-cli profile list and $ nem2-cli account info
b) then generated new profile, 
$ nem2-cli account generate --network MIJIN_TEST -s --url http://localhost:3000 --profile test_profile
Here  $ nem2-cli profile list displays default and test_profiles. 
However 
$ nem2-cli account info --profile test_profile 
$ nem2-cli account info --address <ADDRESS_test_profile>
returms error as mentioned in the first post.
c) then i tried transfering XEM from default (nemesis) into test_profile with command
nem2-cli transaction transfer --recipient  <ADDRESS_test_profile> --message "payout of 10 xem" --mosaics @cat.currency::10000000
In the main display Hash key is displayed along with success info and signer information. However for verification if I run $ nem2-cli account info --profile test_profile 
$ nem2-cli account info --address <ADDRESS_test_profile> commands, I get same error.
Also the output of $ nem2-cli monitor status is also negative for the transaction.

I am really not sure how I can overcome these issues.

I want to make sure the following tasks can be done
a) creation of default and generation (or creation ) of profile/accounts
b) successful transaction transfer 
c) mosaic creation
d) namespace registration and assignment to mosaic 

e) IMPORTANT: validation of all these tasks via
* $ nem2-cli account info --address <ADDRESS>
* $ nem2-cli account info --profile <ProfileName>
* $ nem2-cli monitor [STATUS | confirmed | unconfirmed]

I hope I was able to explain the issues well. for any questions/clarifications, please do send me a message ! Danke

**Comment by rg911** [comment]
@dgarcia360 I haven't look deeper, but when you announce a transfer transaction, it returns invalid version error on 'status` monitor. I think there's something wrong here. That's why @vazudew couldn't see the account info as the new account he created was virgin.

**Comment by dgarcia360** [comment]
Hi @vazudew, try to install the latest version of nem2-cli with ``npm install -g nem2-sdk@latest``. 

How transactions are serialized have changed recently (0.13), and the version you were using was not fully compatible with the latest version of catapult-service bootstrap.

I have been able to query the account info with ``profile`` and ``account``  options.  You can check if the account has received a transaction running ``nem2-cli account transactions --profile ProfileName``. 

@rg911 Successfully sent a transfer transaction using latest version 0.13.0.

**Comment by fboucquez** [comment]
Hi, I'm having a similar problem.

nem2-cli account generate doesn't seem to work. It creates a profile and it says that it has been successfully created an account but then the account is not found via rest or CLI.

nem2-cli account info --profile buyer is returning not found.

![image](https://user-images.githubusercontent.com/5390558/61527141-159e1a80-aa1c-11e9-8770-dca4ac68b24f.png)

I've connected to the mongo db account of the catapult-service-bootstrap and no new records are been added to the account table after running nem2-cli account generate.  

![image](https://user-images.githubusercontent.com/5390558/61527088-fb643c80-aa1b-11e9-839e-22c9a9963826.png)
 
It seems like I can only use the auto-generated (nemesis_addresses) accounts from the generated addresses.yaml

I believe the accounts are not created and transactions to this non-account go nowhere.

**Comment by dgarcia360** [comment]
@fboucquez The public key is recorded in the network when the account first sends or receives a transaction. The nem2-cli generates a private key without interacting with the blockchain.

Try to send some cat.currency (1000 in the following example) from one of the nemesis_accounts to the account you just have created.

`` nem2-cli transaction transfer --recipient <new-address> --mosaics @cat.currency::1000000000 ``

Guide: https://nemtech.github.io/guides/transaction/sending-a-transfer-transaction.html

**Comment by fboucquez** [comment]
Thanks @dgarcia360, that fixed the missing account.
