### ISSUE TITLE
Add the option to register root namespaces when running interactive namespace creation command

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#5]
**1. Expected behavior and actual behavior.**

When running `nem2-cli transaction namespace`, the terminal asks to specify a parent namesapce without having the possibility to say if we want to create a root namespace or subnamespace.

- Introduce namespace name: 
- Introduce the Parent name: 

It should be better to have an option to say if we want to register a root namespace (R) or subnamespace (S), and then, if it is subnamespace ask for the parent name.

**2. Steps to reproduce the problem.**
`nem2-cli transaction namespace`

**3. Version**
nem2-cli 0.9.5

**Comment by guillemsole** [comment]
Fixed in v0.9.7
