### ISSUE TITLE
Failure_Core_Invalid_Version while creating Mosaics

### ISSUE THREAD

**Issue by vazudew** [nemtech/nem2-cli#50]
Ubuntu : 18.04
Nem2cli : 0.12.1
Docker : 18.09.7 Build 2d0083d
(Installation Info: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04 )
Docker-Compose : 1.21.2 Build a133471

Steps
1. catapult-service-bootstrap.git latest cloned and readied
2. exeucted  $ start-all -b -d successfully, all dockers are up
3. valid output received for curl http://localhost:3000/block/1
4. from the address.yaml, grabbed a private key below nemesis_address section
5. created a "default" profile on http://localhost:3000, with Private key from step 4
6. On other terminals opened $ nem2-cli monitor status, $nem2-cli monitor confirmed and $ nem2-cli monitor unconfirmed
7. tried to create mosaics with this command
$  nem2-cli transaction mosaic --amount 1000000 --transferable --supplymutable --divisibility 0 --duration  100000 
The terminal displays messages that transaction announced correctly, with all Hash, Signer, Mosaic information
8. However on the terminal with $ nem2-cli monitor status i get following error
Hash : <HASH OF THE MOSAIC TRANSACTION>
Error Code : Failure_Core_Invalid_Version
Deadline : Timestamp

**Comment by rg911** [comment]
Hi @vazudew 

All transaction versions have been reset. This is one of the latest change of `Elephant` milestone. TS SDK has been updated recently (v0.13) as first Elephant compatible version but cli hasn't been updated with that version yet. 

You can probably build your local docker images by tagging the previous version. or perhaps wait for the cli to be updated.

**Comment by vazudew** [comment]
Hi @rg911 
Thank you very much for your response. 

May be I will wait until next CLI is updated and released.  Any idea, when that might be ?

regards,
V

**Comment by vazudew** [comment]
1. I  tried tagging previous version of dockers with file 
~\catapult-service-bootstrap\cmds\docker\docker-compose.yml
2. updated techbureau/catapult-tools:gcc-0.4.0.1 & techbureau/catapult-rest-server:1.0.15 for previous version tags.
3. executed again nem2-cli profile, nem2-cli transaction commands 
4. In the main display it was showed successful but for $ nem2-cli monitor status following message was displayed

monitoring SBUQSX-J5B5TV-PLBF6A-FEFQNI-VXCOL5-7VMPRH-ZVHV using http://localhost:3000
connection open

Hash: F721DFCE3FE719A9EDC2684F41F85D58654E73CCE30A822FA2EC8440EB585A23
Error code: unknown status 0x80430008
Deadline: 2019-07-05 13:22:48.963

Hash: 2D20192E3993447A316C5C942675F4980C4B6878F62959C956357BAFCB8CB5B6
Error code: unknown status 0x80430008
Deadline: 2019-07-05 13:23:29.858

I am not sure tagging previous versions can work. Do you have any other workarounds ? 
Many thanks for reading and your patience.

**Comment by dgarcia360** [comment]
#52 should solve this.

**Comment by dgarcia360** [comment]
You can try the latest version running ``npm -g nem2-cli@latest". Let us know if you still have the same problem!

**Comment by vazudew** [comment]
Hi All,

Thank you very much for your response. Today things were really positive with new nem2-cli version 0.13.0.

I. Cleaning Setup:
=========
[cleaned entire system of older items such as docker containers, catapult repo etc.]
a) Pruned all system wide docker components
b) removed folder catapult-service-bootstrap.gi and cloned new repo
c)  $ npm install -g nem2-cli@latest   #installs 0.13.0
d) $ nem2-cli start-all -b -d
e) CONFIRMATION:  with $ curl http://localhost:3000/block/1  (success)
f) removed older ~/.nem2

II Tasks - executed these tasks in the same sequence.
========
A. [Prorfles creation]
1)  grabbed one private key under nemesis_generation section of builds/generated*/address.yml
2) created default profile, $ nem2-cli profile create with primary key
3) CONFIRMATION: $ nem2-cli account info (success)
4) generated new a/c : $ nem2-cli account generate --network MIJIN_TEST -s --url http://localhost:3000 --profile test1
5) CONFIRMATION: $ nem2-cli account info --profile test1 (FAIL, virgin account , error message 404)

B. [Anouncing Transaction]
1) nem2-cli transaction transfer --recipient ADDRESS_TEST1 -message "payout of 10 xem" --mosaics @cat.currency::10000000
Main terminal displayed success.. also terminal with $ nem2-cli monitor confirmed Terminal displayed success
2) CONFIRMATION: $ nem2-cli account info --profile test1 (SUCCESS, mosaic info updated) 

C. [Mosaic generation]
1. $ nem2-cli transaction mosaic --amount 1000000 --transferable --supplymutable --divisibility 0 --duration  100000
Main terminal displays success
2. CONFIRMATION:  $ nem2-cli mosaic info -h HEX-MOS (Success)
These mosaics always get owned by DEFAULT profile ? (WHY) 

*Here I want to somehow "transfer" generated mosaics to my custom profile test1*
D. [namespace generation]
1) $ nem2-cli transaction namespace --rootnamespace --duration 100000 --name testns
main terminal displays success
2) CONFIRMATION: nem2-cli namespace info --uint [XXX,YYYY] (Success)
nem2-cli namespace info --name testns (Success)

E. [Link Mosaic to a namespace]
1. $ nem2-cli transaction mosaicalias --action 0 --mosaic ID_MOS --namespace testns
Confirmation is displayed on main terminal

F. [Link Namespace to Address]
1. $ nem2-cli transaction addressalias --action 0 --address TEST1_ADDRESS --namespace testns
I get an error something like "Failure_Namespace_Alias_Already_exists" 

Can I somehow generate mosaics for non-default accounts via linking mosaics to namespace and then to non-default address`?

**Comment by vazudew** [comment]
#50 can be closed as new version is able to handle lot of issues, observed earlier :)
please have a look at #54 
Thanks,
