### ISSUE TITLE
Can I link Namespace with linked Mosaics, to a non default Profile/Account ?

### ISSUE THREAD

**Issue by vazudew** [nemtech/nem2-cli#54]
Hi All,

Thank you very much for your response. Today things were really positive with new nem2-cli version 0.13.0.

### I. Cleaning Setup:

> cleaned entire system of older items such as docker containers, catapult repo etc.

a) Pruned all system wide docker components
b) removed folder catapult-service-bootstrap.gi and cloned new repo
c) $ npm install -g nem2-cli@latest #installs 0.13.0
d) $ nem2-cli start-all -b -d
e) CONFIRMATION: with $ curl http://localhost:3000/block/1 (success)
f) removed older ~/.nem2

### II Tasks - executed these tasks in the same sequence.

A. [Profiles creation]

- grabbed one private key under `nemesis_generation` section of `builds/generated*/address.yml`
- created default profile, `$ nem2-cli profile create` with primary key

CONFIRMATION: 
`$ nem2-cli account info` (success)

- generated new a/c : `$ nem2-cli account generate --network MIJIN_TEST -s --url http://localhost:3000 --profile test1`

CONFIRMATION: 
`$ nem2-cli account info --profile test1` (**FAIL, virgin account , error message 404**)

B. [Announcing Transaction]

`$ nem2-cli transaction transfer --recipient ADDRESS_TEST1 -message "payout of 10 xem" --mosaics @cat.currency::10000000`

Main terminal displayed success.. also terminal with $ nem2-cli monitor confirmed Terminal displayed success

CONFIRMATION: 
`$ nem2-cli account info --profile test1` (SUCCESS, mosaic info updated)

C. [Mosaic generation]

`$ nem2-cli transaction mosaic --amount 1000000 --transferable --supplymutable --divisibility 0 --duration 100000`

Main terminal displays success

CONFIRMATION: 
`$ nem2-cli mosaic info -h HEX-MOS` (Success)

**These mosaics always get owned by DEFAULT profile ? (WHY)**

Here I want to somehow "transfer" generated mosaics to my custom profile test1

D. [namespace generation]

`$ nem2-cli transaction namespace --rootnamespace --duration 100000 --name testns`

Main terminal displays success

CONFIRMATION: 
`$ nem2-cli namespace info --uint [XXX,YYYY]` (Success)
`$ nem2-cli namespace info --name testns` (Success)

E. [Link Mosaic to a namespace]

`$ nem2-cli transaction mosaicalias --action 0 --mosaic ID_MOS --namespace testns`

Confirmation is displayed on main terminal

F. [Link Namespace to Address]

`$ nem2-cli transaction addressalias --action 0 --address TEST1_ADDRESS --namespace testns`

I get an error something like `Failure_Namespace_Alias_Already_exists`

Can I somehow generate mosaics for non-default accounts via linking mosaics to namespace and then to non-default address`?

[EDIT by @evias]: Formatting issue description.

**Comment by evias** [comment]
> These mosaics always get owned by DEFAULT profile ? (WHY)

You are executing the Mosaic definition with : `$ nem2-cli transaction mosaic --amount 1000000 --transferable --supplymutable --divisibility 0 --duration 100000`

You have to add `--profile test1` if you want `test1` to be the owner.

-- 

> I get an error something like Failure_Namespace_Alias_Already_exists

An alias can only relate to *one object at a time*. It can relate _to an address_ **or** _to a mosaic id_ but not both together.

In the step before getting this error, you affect `testns` the mosaic alias for ID_MOS. So that means that this namespace relates to a _mosaic_ now.

You can only link to one object for one namespace ; but one object can be linked to by multiple namespaces. :+1:

I believe this issue can be closed.

**Comment by vazudew** [comment]
> An alias can only relate to one object at a time. It can relate to an address or to a mosaic id but not both together.

$ nem2-cli transaction addressalias --action 0 --address SCEKUG-H2IJBF-7JZRNK-ECMW52-E66SZ6-ODLB4W-NI7K --namespace foo
Source : https://nemtech.github.io/cli.html
Section : Link a namespace to an address
