### ISSUE TITLE
nem2-cli transaction mosaic does not validate if the account exists

### ISSUE THREAD

**Issue by fboucquez** [nemtech/nem2-cli#59]
This issue is related to https://github.com/nemtech/nem2-cli/issues/49

I've used nem2-cli account generate command to create an account. Although the operation said success, the account wasn't really created.

Then I tried to add a mosaic to the "generated" account. The command also said that the operation was a success and showed me the mosaic id.  

But it seems like the mosaic operation hasn't done anything. The mosaic hasn't been created in reality

![image](https://user-images.githubusercontent.com/5390558/61529665-39fcf580-aa22-11e9-8813-11e69c44f9da.png)

I'm not sure if the problem is the CLI or the server that is returning this false positive. 

Expected outcome:
The operation should fail stating that the account doesn't exist in the system. 

Note:
Nothing is shown in the nem2-cli monitor unconfirmed or nem2-cli monitor confimed logs when using the invalid account. If I add a new mosaic to an existing account, I can see that transaction in the monitors

**Comment by dgarcia360** [comment]
Thanks for sending your feedback!

**Account generation**

The [public key](https://nemtech.github.io/concepts/account.html#) is recorded in the network when the account first sends or receives a transaction. The nem2-cli generates a private key without interacting with the blockchain.

**Mosaic creation**

1. To create a mosaic, [you need cat.currency](https://nemtech.github.io/concepts/mosaic.html#cost). Try [transferring some cat.currency](https://nemtech.github.io/concepts/mosaic.html#cost) from one of the nemesis accounts to the account you have created.  

2. Receiving an OK from the REST API [does not mean that the transaction is included in the block](https://nemtech.github.io/concepts/transaction.html#announcing-a-transaction).

``Transaction announced correctly`` means that the transaction was well-formed and that the network received it.  As you mention in the note, to validate the status of the transaction you have to [monitor the transaction status](https://nemtech.github.io/guides/transaction/monitoring-a-transaction-status.html). Once the new account receives the transaction mentioned in 1 with cat.currency, you will be able to monitor it.

@NEMTechCN @evias To enhance the developer experience, we can add the following message after announcing a transaction: 

> Warning: The network has not confirmed the transaction. Remember to monitor the transaction status.

**Comment by fboucquez** [comment]
Thanks @dgarcia360. I'm new in NEM and blockchain in general.

Once I transferred some mosaics from the nemesis account to generated account, the new account is now in the system. 

nem2-cli account info --profile seller

Now returns information about the account.

So the steps to give a new mosaic to a generated account are 
1) Create the mosaics in the nemesis-account 
2) Transfer the mosaic from the nemesis account to the new account. 

It's not possible to create a new mosaic into the generated account directly right?

I have just tried re-running the command 

nem2-cli transaction mosaic --amount 555 --supplymutable  --duration 100 --profile seller

and the mosaic doesn't appear in the existing generated account.

Would it be possible to add a comment to the documentation and/or a warning to the command after checking that the recipient of the nem2-cli transaction mosaic is not a nemesis account?

Thanks!
Fernando

**Comment by dgarcia360** [comment]
Hi @fboucquez,

> It's not possible to create a new mosaic into the generated account directly right?

It is possible. The new account ``seller`` needs to have enough  ``cat.currency`` - the mosaic to pay the service fees.  By default, creating a mosaic costs [500 cat.currency](https://nemtech.github.io/concepts/mosaic.html#cost). 

You can transfer ``cat.currency`` from a ``nemesis_account`` to the new account you have created.

Running the command above you will be transferring ``10,000 cat.currency`` from the nemesis account to the new account seller:

```
nem2-cli transaction transfer --recipient <seller-address> --mosaics @cat.currency::10000000000 --profile nemesis_account
```

Note that 10,000 is written 10000000000, because the cli use absolute amounts. To get an absolute amount, multiply the amount of assets you want to send by 10^divisibility. In this case, cat.currency has divisibility 6, so 10,000 * 10^6 = 10000000000.

After the seller account receives the transfer transaction, try to create a mosaic with your account. You can query the status of the transaction at any time running the following command:

```
nem2-cli transaction info --hash <transaction-hash>
```

**Comment by dgarcia360** [comment]
I close the issue, let me know if you don't manage to create the mosaic from the new account.

**Comment by fboucquez** [comment]
HI @dgarcia360. I'm sorry for the late response. 

I've managed to create mosaics on the new account. Thanks so much!

> The nem2-cli generates a private key without interacting with the blockchain.

Does it seem like  `nem2-cli account generate` is technically generating a key pair instead of an account? The account is "alive" once is in the blockchain after receiving cat.currency. Maybe the command should be called ` nem2-cli key generate` or  `nem2-cli profile generate`?
