### ISSUE TITLE
Add mutable option when running the interactive command for creating mosaics

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#6]
**1. Expected behavior and actual behavior.**

When running `nem2-cli transaction mosaic`, the terminal is not asking if the mosaic should be mutable or not.

**2. Steps to reproduce the problem.**
`nem2-cli transaction mosaic`

**3. Version**
nem2-cli 0.9.5

**Comment by guillemsole** [comment]
Fixed in v0.9.7
