### ISSUE TITLE
Transactions Performance Improvement - Query

### ISSUE THREAD

**Issue by hulekal123** [nemtech/nem2-cli#65]
Hello All,

Currently I am using latest SDK and CLI for development of a web application using NEM. 

Unfortunately the speed with which Transactions do happen, is slow for our needs.

Are there any mechanisms or measures, so that I can fasten this process ?

I was suggested to increase the number of Peer Nodes in order to improve performance. 
- Does that really work ? 
- If yes, what exactly I need to do, so I can increase the nodes to cater to better speed without affecting functionality?
- Additionally I have not found any documentation or sources to help me with this regard.

Any leads will be greatly appreciated. Thank you.

**Comment by evias** [comment]
Hello there,

Not sure if that is of help but block time can be configured by network in catapult config. Not sure about safety of decreasing it but you should be able to win some here in case you are talking about "transaction confirmation speed".

In case you are speaking about transaction broadcasting delay, i would suggest you indeed augment capacities of your node and potentially add more nodes in network to ensure faster throughput.

Also, it is good practice to broadcast txes to multiple nodes in p2p networks, depending on the node's capacities (RAM, CPU, etc..), i imagine you can probably improve delivery time.
