### ISSUE TITLE
Support mosaic global restriction transaction

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#73]
## MosaicGlobalRestrictionTransaction

Set a [global restriction](https://nemtech.github.io/concepts/mosaic-restriction.html#mosaicglobalrestrictiontransaction) to a mosaic.

### Command

``nem2-cli transaction mosaicglobalrestriction``

| param | type | description | default |
| -- | -- | -- | -- | 
| --profile | string | (Optional) Select between your profiles, by providing a profile  | |
| --maxFee | uint | (Optional) Maximum fee | 0 |
| --mosaicId | hex | Identifier of the mosaic being restricted | |
| --referenceMosaicId | hex | (Optional) Identifier of the mosaic providing the restriction key | 0 |
| --restrictionKey | hex | Restriction key relative to the reference mosaic identifier | |
| --previousRestrictionValue | hex | (Optional) Previous restriction value. | None |
|--previousRestrictionType | int |  (Optional) Previous restriction type | 0 |
|--newRestrictionValue | hex |  New restriction value | |
| --newRestrictionType | int | New restriction type | |

**Comment by NemTechCN** [comment]
PR #109
