### ISSUE TITLE
Support multisig modification transaction

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#79]
## MultisigModificationTransaction

This specification would only allow adding/removing one cosignatory at a time. Please, comment on the issue if you have an idea to support multiple actions at a time.

Create or modify a multisig contract.

### Command

``nem2-cli transaction multisigmodification``

| param | type | description | default | 
| -- | -- | -- | -- |
| --profile | string | (Optional) Select between your profiles, by providing a profile  | default |
| --maxFee | uint | (Optional) Maximum fee | 0 |
| --minRemovalDelta | int | (Optional) Number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. | 0 |
| --minApprovalDelta | int | (Optional) Number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. | 0 |
| --action | uint | Modification Action (1: Add, 0: Remove). | |
| --cosignatoryPublicKey | string | Cosignatory account public key. | |

**Comment by NemTechCN** [comment]
@dgarcia360 
I think I need a parameter which refers the multisig account public key to create multisig account

**Comment by NemTechCN** [comment]
PR #126
