### ISSUE TITLE
Refactor parameters name

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#80]
* Rename commands names and properties to be aligned with the latest elephant 3 schema changes.
* Allow camelCase property names.

**Comment by NemTechCN** [comment]
@dgarcia360 

PR #101

**Comment by dgarcia360** [comment]
Hi @NemTechCN, I assigned myself this issue, here is the PR #102. I'll review what you have done and check if there is something new we could include.

To assign yourself to new issues, please accept the invitation I have sent a while ago to join the project. If you didn't receive the email, log in with @NemTechCN account and open https://github.com/nemtech/nem2-cli/. You should see some pop-up to join the repo. Thanks!

**Comment by NemTechCN** [comment]
@dgarcia360 

I logged in with the @NemTechCN  account and opened https://github.com/nemtech/nem2-cli/.
But I haven't received the message that pop-up to join the repo yet.

**Comment by dgarcia360** [comment]
@NemTechCN sorry, try with https://github.com/nemtech/nem2-cli/invitations

**Comment by NemTechCN** [comment]
Joined it , thank you
