### ISSUE TITLE
Update nem2-sdk (elephant 3)

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#81]
Update nem2-cli to be compatible with nem2-sdk 0.13.2

**Comment by dgarcia360** [comment]
Changes being applied by @NemTechCN

**Comment by NemTechCN** [comment]
@dgarcia360 
Some command goes wrong after updating nem2-sdk to version 0.13.2.

I've checked the parameters all the time, but I can't find any problem. I rollback to version `0.13.1`, these commands does work again.

I'm not sure whether the SDK or REST server is heathy.

**Example**
1.create a profile saving as Alice:
`nem2-cli account generate -n MIJIN_TEST -u http://47.107.245.217:3000 --profile Alice -s`

2.Error:
`TypeError: str.substring is not a function`
`Error Provide a valid NEM2 Node URL. Example: http://localhost:3000`

**Comment by dgarcia360** [comment]
@NemTechCN Thanks for reporting. Could you submit the PR? I can try to reproduce the issue. Thanks!

**Comment by NemTechCN** [comment]
@dgarcia360 

PR #99
