### ISSUE TITLE
Support secretlock / secretproof transactions

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#83]
## SecretLock

Start a [token swap](https://nemtech.github.io/guides/secretlock/atomic-cross-chain-swap-between-NEM-public-and-private-chain.html) between different chains.

### Command

``nem2-cli transaction secretlock``

| param | type | description | default |
| -- | -- | -- | -- | 
| --profile | string | (Optional) Select between your profiles, by providing a profile  |  default |
| --maxFee | uint | (Optional) Maximum fee | 0 |
| --mosaicId | hex | Locked mosaic | |
 --amount | uint | (Optional) Amount to lock  |   |
| --duration | uint |  Number of blocks for which a lock should be valid. Duration is allowed to lie up to ``30`` days. If reached, the mosaics will be returned to the initiator | |
| --hashAlgorithm | string | [Algorithm used to hash the proof](https://nemtech.github.io/concepts/cross-chain-swaps.html#lockhashalgorithm) |  |
| --secret | string | Proof hashed |  |
| --recipientAddress | string | Address that receives the funds once unlocked |  |

**Comment by NemTechCN** [comment]
@dgarcia360 

## SecretLock

If we want to swap tokens between two differrent chains, we need two more parameters——`privateKey` and `url` as follows:

|param|type|description|default|
|-|-|-|-|
|privateKey|string|The private key of an account on the other chain.(If Alice(public chain) want to send 10 tokens to Bob (Private chain), this private key means an account created by Alice on Bob's private chain)| |
|url|string|The url of the other chain. (The url of the other chain)|

**Comment by NemTechCN** [comment]
I forgot one——`networkType`

|param|type|description|default|
|-|-|-|-|
|networkType|string|The network type of the other chain.(e.g. MIJIN_TEST...)

And, there are some useless params in creating a secretproof transaction.

**Comment by NemTechCN** [comment]
PR #127
