### ISSUE TITLE
Support persitent harvesting delegation transaction

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/nem2-cli#85]
Info : [Delegated harvesting](https://friendly-poincare-94964d.netlify.com/concepts/harvesting.html#delegated-harvesting)

Add to ``transaction transfer`` command a new flag ``--persistentHarvestingDelegation``, and ``--recipientPublicKey`` to pass the node's public key.

The message field accepts the private key of a remoteAccount, encrypting it before signing the transaction using the following function: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/cea9709039d216dd386ab9ca2b47b40f8bbdbb3b/src/model/message/PersistentHarvestingDelegationMessage.ts#L40

**Comment by NemTechCN** [comment]
Could you describe these parameters more clear? I'm not sure how to use these parameters.

**Comment by NemTechCN** [comment]
I think we should make this function an independent command.

I try to add this function to `transaction transfer`, but there are too many useless parameters.

**Comment by dgarcia360** [comment]
@NemTechCN Sounds like a good idea. Here you can get a code example on how to implement this feature: https://github.com/nemtech/nem2-docs/pull/276/files#diff-e685f019ba7ebfa3016e6bc2a499c1a4
